### ISSUE TITLE
firebase database rules unclear

### ISSUE THREAD

**Issue by gianlazz** [cbetz/my-stuff#1]
"Set the database rules by clicking Database, then the Rules tab. Use the configuration below" from the read me mentions a configuration but it is unclear where or if that is on the readme

**Comment by gianlazz** [comment]
read and write should be set as true?

```
{
  "rules": {
    ".read": true,
    ".write": true
  }
}
```

**Comment by cbetz** [comment]
@gianlazz Correct! Thanks for pointing that out! Copy+paste error from my Medium article. Updated the README.
